version: '3'
services:
  web:
    image: node-mysql-crud-app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"